create database com;

use com;

CREATE TABLE customers (
    customer_id INT PRIMARY KEY,
    first_name VARCHAR(50),
    last_name VARCHAR(50),
    email VARCHAR(100) UNIQUE,
    city VARCHAR(50)
);

CREATE TABLE orders (
    order_id INT PRIMARY KEY,
    customer_id INT,
    product VARCHAR(100),
    amount DECIMAL(10,2),
    order_date DATE,
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
);


INSERT INTO customers (customer_id, first_name, last_name, email, city) VALUES
(1, 'John', 'Smith', 'john@example.com', 'New York'),
(2, 'Emily', 'Johnson', 'emily@example.com', 'Los Angeles'),
(3, 'Michael', 'Brown', 'michael@example.com', 'Chicago'),
(4, 'Sarah', 'Davis', 'sarah@example.com', 'Houston'),
(5, 'DORA', 'SORA', 'SORA@example.com', 'Houston');


INSERT INTO orders (order_id, customer_id, product, amount, order_date) VALUES
(106, 3, 'Keyboard', 45.00, '2024-03-01'),
(107, 2, 'USB Cable', 10.00, '2024-03-05'),
(108, 3, 'Webcam', 70.00, '2024-03-10'),
(109, 1, 'Tablet', 320.00, '2024-03-15'),
(110, 4, 'Office Lamp', 35.00, '2024-03-20'),
(111, 2, 'Phone Charger', 18.00, '2024-03-25'),
(112, 3, 'Microphone', 95.00, '2024-04-01'),
(113, 1, 'External Hard Drive', 85.00, '2024-04-05'),
(114, 4, 'Printer', 160.00, '2024-04-10'),
(115, 2, 'Smartwatch', 200.00, '2024-04-12');

select * from customers;
select * from orders;
-- RETURN ALL CUSTOMER DETAILS WHO PLACED ORDERS
SELECT ORDERS.CUSTOMER_ID, CONCAT(FIRST_NAME, ' ', LAST_NAME) AS FULLNAME,
		ORDER_ID, AMOUNT, ORDER_DATE 
FROM CUSTOMERS
RIGHT JOIN ORDERS
ON CUSTOMERS.CUSTOMER_ID = ORDERS.CUSTOMER_ID;
-- RETURN ALL CUSTOMERS ORDERS 
SELECT CUSTOMERS.CUSTOMER_ID, CONCAT(FIRST_NAME, ' ', LAST_NAME) AS FULLNAME,
		ORDER_ID, AMOUNT, ORDER_DATE 
FROM CUSTOMERS
LEFT JOIN ORDERS
ON CUSTOMERS.CUSTOMER_ID = ORDERS.CUSTOMER_ID;

-- FULL JOIN 
-- RETURN ALL RECORDS FROM TWO TABLES
(SELECT ORDERS.CUSTOMER_ID, CONCAT(FIRST_NAME, ' ', LAST_NAME) AS FULLNAME,
		ORDER_ID, AMOUNT, ORDER_DATE 
FROM CUSTOMERS
RIGHT JOIN ORDERS
ON CUSTOMERS.CUSTOMER_ID = ORDERS.CUSTOMER_ID)
UNION
(SELECT CUSTOMERS.CUSTOMER_ID, CONCAT(FIRST_NAME, ' ', LAST_NAME) AS FULLNAME,
		ORDER_ID, AMOUNT, ORDER_DATE 
FROM CUSTOMERS
LEFT JOIN ORDERS
ON CUSTOMERS.CUSTOMER_ID = ORDERS.CUSTOMER_ID);

-- COUNT EACH CUSTOMER TOTAL ORDERS
SELECT CUSTOMERS.CUSTOMER_ID, CONCAT(FIRST_NAME, ' ', LAST_NAME) AS FULLNAME,
		COUNT(ORDERS.ORDER_ID) AS TOTAL_ORDERS
FROM CUSTOMERS
LEFT JOIN ORDERS
ON CUSTOMERS.CUSTOMER_ID = ORDERS.CUSTOMER_ID
GROUP BY CUSTOMERS.CUSTOMER_ID;
-- FIND EACH CUSTOMERS TOTAL SPEND ON ODERS
SELECT ORDERS.CUSTOMER_ID, CONCAT(FIRST_NAME, ' ', LAST_NAME) AS FULLNAME,
		SUM(AMOUNT) AS TOTAL_AMOUNT_SPEND
FROM CUSTOMERS
RIGHT JOIN ORDERS
ON CUSTOMERS.CUSTOMER_ID = ORDERS.CUSTOMER_ID
GROUP BY ORDERS.CUSTOMER_ID;
-- FIND EACH CUSTOMRS LAST ORDERED DATE
SELECT * FROM ORDERS;
SELECT ORDERS.CUSTOMER_ID, CONCAT(FIRST_NAME, ' ', LAST_NAME) AS FULLNAME,
		MAX(ORDER_DATE) AS LATEST_ORDER_DATE
FROM CUSTOMERS
RIGHT JOIN ORDERS
ON CUSTOMERS.CUSTOMER_ID = ORDERS.CUSTOMER_ID
GROUP BY ORDERS.CUSTOMER_ID;

SELECT * FROM ORDERS;

-- FIND EACH CUSTOMERS FIRST ORDERED DATE
SELECT ORDERS.CUSTOMER_ID, CONCAT(FIRST_NAME, ' ', LAST_NAME) AS FULLNAME,
		MIN(ORDER_DATE) AS LATEST_ORDER_DATE
FROM CUSTOMERS
RIGHT JOIN ORDERS
ON CUSTOMERS.CUSTOMER_ID = ORDERS.CUSTOMER_ID
GROUP BY ORDERS.CUSTOMER_ID;
--  RETURN ALL COUSTOMERS DETAILS WHO PLACED MORETHAN ONE ORDER
SELECT CUSTOMERS.CUSTOMER_ID, CONCAT(FIRST_NAME, ' ', LAST_NAME) AS FULLNAME,
		COUNT(ORDERS.ORDER_ID) AS TOTAL_ORDERS
FROM CUSTOMERS
LEFT JOIN ORDERS
ON CUSTOMERS.CUSTOMER_ID = ORDERS.CUSTOMER_ID
GROUP BY CUSTOMERS.CUSTOMER_ID
having TOTAL_ORDERS >= 1;