-- create new database VIEWS
CREATE DATABASE VIE;

USE VIE;

CREATE TABLE Department (
    DeptID INT PRIMARY KEY,
    DeptName VARCHAR(50),
    Location VARCHAR(50)
);

INSERT INTO Department (DeptID, DeptName, Location) VALUES
(101, 'Human Resources', 'New York'),
(102, 'Finance', 'Chicago'),
(103, 'IT', 'San Francisco'),
(104, 'Marketing', 'Boston');


CREATE TABLE Employee (
    EmpID INT PRIMARY KEY,
    EmpName VARCHAR(50),
    Age INT,
    Salary DECIMAL(10,2),
    DeptID INT,
    JoinDate DATE,
    FOREIGN KEY (DeptID) REFERENCES Department(DeptID)
);

INSERT INTO Employee (EmpID, EmpName, Age, Salary, DeptID, JoinDate) VALUES
(1, 'John Doe', 29, 55000, 101, '2020-01-15'),
(2, 'Sarah Lee', 34, 68000, 102, '2019-09-30'),
(3, 'Mike Ross', 41, 82000, 103, '2018-03-12'),
(4, 'Emma Stone', 27, 48000, 104, '2021-07-22'),
(5, 'Kevin Hart', 31, 60000, 103, '2020-11-01'),
(6, 'Olivia King', 38, 75000, 102, '2017-05-10'),
(7, 'Liam Smith', 25, 45000, 101, '2022-02-14'),
(8, 'Ava Brown', 30, 70000, 104, '2020-08-05'),
(9, 'David Park', 44, 92000, 103, '2016-12-19'),
(10, 'Nora Green', 33, 65000, 101, '2021-04-03');


SELECT * FROM EMPLOYEE;
SELECT * FROM DEPARTMENT;

-- SYNTAX FOR CREATE VIEW: CREATE VIEW VIEW_NAME AS 
-- 							SELECT COLUMN_NAMES FROM TABLE_NAME
-- 							WHERE CONDITION;

-- CREATE EMPLOYEE_VIEW
CREATE VIEW EMPLOYEE_VIEW AS
SELECT EMPID, EMPNAME, DEPTID, JOINDATE FROM EMPLOYEE;
-- SELECT DATA FROM EMPLOYEE_VIEW
SELECT * FROM EMPLOYEE_VIEW;

-- INSERT ONE RECORD INTO EMPLOYEE TABLE
INSERT INTO Employee (EmpID, EmpName, Age, Salary, DeptID, JoinDate) VALUES
(11, 'BABU', 29, 55000, 101, '2020-01-15');

-- CHECK VIEW DATA
SELECT * FROM EMPLOYEE_VIEW;

-- CREATE HIGHER_SALARY_EMPLOYEE IN THAT, WHOES SALARY IS MORRETHAN 60000
CREATE VIEW HIGHER_SALARY_EMPLOYEE AS
SELECT EMPID, EMPNAME, DEPTID FROM EMPLOYEE
WHERE SALARY > 60000;

-- CHECK HIGHER_SALARY_EMPLOYEE VIEW TABLE DATA
SELECT * FROM HIGHER_SALARY_EMPLOYEE;

-- CREATE EMPLOYEE_INFO
CREATE VIEW EMPLOYEE_INFO AS 
SELECT E.EMPID, E.EMPNAME, D.DEPTNAME, D.LOCATION FROM EMPLOYEE E
LEFT JOIN DEPARTMENT D
ON E.DEPTID = D.DEPTID;

-- CHECK DATA IN EMPLOYEE_INFO VIEW
SELECT * FROM EMPLOYEE_INFO;

-- SELECT EMPLOYEES THOES ARE BELONGS TO 'New York'
SELECT * FROM EMPLOYEE_INFO
WHERE LOCATION = 'New York';


-- ALTER THE EMPLOYEE_INFO VIEW
ALTER VIEW EMPLOYEE_INFO AS
SELECT EMPID, EMPNAME, DEPTID FROM EMPLOYEE;

SELECT * FROM EMPLOYEE_INFO;

-- DELETE HIGHER_SALARY_EMPLOYEE VIEW
DROP VIEW HIGHER_SALARY_EMPLOYEE;